name: Pull Request Title Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
permissions: read-all
jobs:
  check-pr-title:
    name: check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        run: |
          title=$(jq --raw-output .pull_request.title $GITHUB_EVENT_PATH)
          if [ $(echo $title | grep -Eoc '^(feat|fix|chore|docs|test|build)(\([a-zA-Z0-9\-]+\))?: .{1,100}+$') -eq 0 ]; then # https://regex101.com/r/swQ454/1
             echo "PR title does not comply with conventional commits"
             echo "PR title does not comply with conventional commits: $(cat pull-request-title/title)" > comment/comment
             exit 1
          fi
