name: Smoke Test
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build all packages
    runs-on: ubuntu-latest

    steps:
      - name: Setup git
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      # update container FS permissions to allow scripts to build dist files and allow lerna to bootstrap
      # `find` command lists all dirs in src and runs the permission update on them
      - name: set file permissions
        run: find src/ -type d -exec chmod 777 {} +

      - name: Test solid library build
        run: pnpm build:solid:lib

      - name: Test solid docs build
        run: pnpm build:solid:docs
